/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class site_ycsb_db_CMyKVClient */

#ifndef _Included_site_ycsb_db_CMyKVClient
#define _Included_site_ycsb_db_CMyKVClient
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     site_ycsb_db_CMyKVClient
 * Method:    cInit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_site_ycsb_db_CMyKVClient_cInit
  (JNIEnv *, jobject);

/*
 * Class:     site_ycsb_db_CMyKVClient
 * Method:    cGet1s
 * Signature: (JLjava/lang/String;ILsite/ycsb/db/KVReply;)I
 */
JNIEXPORT jint JNICALL Java_site_ycsb_db_CMyKVClient_cGet1s
  (JNIEnv *, jobject, jlong, jstring, jint, jobject);

/*
 * Class:     site_ycsb_db_CMyKVClient
 * Method:    cGet2s
 * Signature: (JLjava/lang/String;ILsite/ycsb/db/KVReply;)I
 */
JNIEXPORT jint JNICALL Java_site_ycsb_db_CMyKVClient_cGet2s
  (JNIEnv *, jobject, jlong, jstring, jint, jobject);

/*
 * Class:     site_ycsb_db_CMyKVClient
 * Method:    cPut
 * Signature: (JLjava/lang/String;ILsite/ycsb/db/KVReply;)I
 */
JNIEXPORT jint JNICALL Java_site_ycsb_db_CMyKVClient_cPut
  (JNIEnv *, jobject, jlong, jstring, jint, jobject);

/*
 * Class:     site_ycsb_db_CMyKVClient
 * Method:    cDel
 * Signature: (JLjava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_site_ycsb_db_CMyKVClient_cDel
  (JNIEnv *, jobject, jlong, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
